// breed-data.js — Database razze per specie
// Fonti: FCI (cani), WCF/TICA/FIFe (gatti), ARBA (conigli)

var BREED_DATABASE = {
    "Cane": [
        "Affenpinscher", "Afghan Hound", "Airedale Terrier", "Akita Inu",
        "Alano", "Alaskan Malamute", "American Staffordshire Terrier",
        "Australian Cattle Dog", "Australian Shepherd",
        "Basenji", "Basset Hound", "Bassotto", "Bassotto Nano",
        "Beagle", "Bearded Collie", "Bedlington Terrier",
        "Bichon Fris\u00e9", "Bloodhound", "Bobtail",
        "Border Collie", "Border Terrier", "Borzoi",
        "Boston Terrier", "Bouledogue Francese", "Bovaro del Bernese",
        "Boxer", "Bracco Italiano", "Bracco Tedesco",
        "Bull Terrier", "Bulldog Francese", "Bulldog Inglese", "Bullmastiff",
        "Cairn Terrier", "Cane Corso", "Cane da Pastore Maremmano-Abruzzese",
        "Cavalier King Charles Spaniel", "Chesapeake Bay Retriever",
        "Chihuahua", "Chinese Crested", "Chow Chow",
        "Cirneco dell'Etna", "Cocker Spaniel Americano", "Cocker Spaniel Inglese",
        "Collie", "Coton de Tulear", "Curly-Coated Retriever",
        "Dalmata", "Dobermann",
        "Dogo Argentino", "Dogue de Bordeaux",
        "English Setter", "English Springer Spaniel",
        "Epagneul Breton", "Eurasier",
        "Flat-Coated Retriever", "Fox Terrier",
        "Golden Retriever", "Gordon Setter", "Grand Basset Griffon Vend\u00e9en",
        "Greyhound", "Griffone di Bruxelles",
        "Havanese", "Hovawart", "Husky Siberiano",
        "Irish Red Setter", "Irish Terrier", "Irish Wolfhound",
        "Jack Russell Terrier",
        "Keeshond", "Kerry Blue Terrier", "King Charles Spaniel",
        "Komondor", "Kuvasz",
        "Labradoodle", "Labrador Retriever", "Lagotto Romagnolo",
        "Leonberger", "Lhasa Apso",
        "Maltese", "Manchester Terrier", "Maremma Sheepdog",
        "Mastiff", "Mastino Napoletano",
        "Miniature Pinscher", "Miniature Schnauzer",
        "Norfolk Terrier", "Norwegian Elkhound", "Norwich Terrier",
        "Nova Scotia Duck Tolling Retriever",
        "Papillon", "Pastore Australiano", "Pastore Belga",
        "Pastore del Caucaso", "Pastore Olandese", "Pastore Svizzero Bianco",
        "Pastore Tedesco", "Pechinese", "Petit Basset Griffon Vend\u00e9en",
        "Pinscher", "Pitbull", "Pointer", "Pointer Inglese",
        "Pomerania", "Barboncino", "Barboncino Nano", "Barboncino Toy",
        "Pug",
        "Rhodesian Ridgeback", "Rottweiler",
        "Saluki", "Samoiedo", "San Bernardo",
        "Schnauzer", "Schnauzer Gigante",
        "Scottish Terrier", "Segugio Italiano",
        "Setter Inglese", "Setter Irlandese",
        "Shar-Pei", "Shiba Inu", "Shih Tzu",
        "Siberian Husky", "Silky Terrier", "Skye Terrier",
        "Sloughi", "Soft Coated Wheaten Terrier",
        "Spinone Italiano", "Staffordshire Bull Terrier",
        "Terranova", "Tibetan Mastiff", "Tibetan Spaniel", "Tibetan Terrier",
        "Vizsla", "Volpino Italiano",
        "Weimaraner", "Welsh Corgi Cardigan", "Welsh Corgi Pembroke",
        "Welsh Terrier", "West Highland White Terrier",
        "Whippet", "Wire Fox Terrier",
        "Yorkshire Terrier",
        "Zwergschnauzer",
        "Meticcio"
    ],
    "Gatto": [
        "Abissino", "American Bobtail", "American Curl", "American Shorthair",
        "Balinese", "Bengala", "Birmano", "Blu di Russia", "Bombay",
        "British Longhair", "British Shorthair", "Burmese", "Burmilla",
        "Certosino", "Cornish Rex", "Cymric",
        "Devon Rex", "Don Sphynx",
        "Egyptian Mau", "Europeo", "Exotic Shorthair",
        "Havana Brown", "Highland Fold",
        "Japanese Bobtail",
        "Korat", "Kurilian Bobtail",
        "LaPerm",
        "Maine Coon", "Manx", "Mau Egiziano",
        "Munchkin",
        "Nebelung", "Norvegese delle Foreste",
        "Ocicat", "Orientale",
        "Persiano", "Peterbald", "Pixie-Bob",
        "Ragamuffin", "Ragdoll", "Russian Blue",
        "Sacro di Birmania", "Savannah", "Scottish Fold", "Scottish Straight",
        "Selkirk Rex", "Siamese", "Siberiano", "Singapura",
        "Snowshoe", "Somalo", "Sphynx",
        "Thai", "Tonkinese", "Toyger", "Turkish Angora", "Turkish Van",
        "Meticcio"
    ],
    "Coniglio": [
        "Ariete Nano", "Ariete Francese", "Ariete Inglese",
        "Angora", "Angora Francese",
        "Californiano", "Cincill\u00e0",
        "Dutch (Olandese)",
        "Ermellino", "Rex",
        "Fiammingo Gigante", "Florida White",
        "Hotot", "Hotot Nano",
        "Jersey Wooly",
        "Lionhead (Testa di Leone)",
        "Mini Lop", "Mini Rex", "Mini Satin",
        "Nano Colorato (Netherlandse Dwerg)",
        "Olandese Nano",
        "Polish",
        "Satin",
        "Meticcio"
    ],
    "Altro": []
};

// Helper function: restituisce le razze per una specie
function getBreedsForSpecies(species) {
    if (!species) return [];
    return BREED_DATABASE[species] || [];
}
